Issue 16 discount list
Appitzr-Project/Backend-Discount pull request #2
Opened 2021-05-29 17:01 UTC by hapehatelo

@JuniYadi

2021-06-02 01:23 UTC, JuniYadi requested changes
Silahkan di update dulu

2021-06-02 01:23 UTC, JuniYadi commented on controller/discountController.ts
> +      const queryDB = await ddb.scan(params).promise();
bukan pakai scan, tapi ini lebih ke query data diskon yg punya si venue.

misalnya:

GET /venue/:venueId

jadi list diskon dari punya si venue tersebut yg muncul, bukan global semua diskon.

2021-06-02 12:28 UTC, hapehatelo commented
udah aku update @JuniYadi 
ini untuk diakses public kan?

2021-06-03 06:07 UTC, JuniYadi commented
> udah aku update @JuniYadi
> ini untuk diakses public kan?

bukan, ini di akses venue

2021-06-03 06:09 UTC, JuniYadi commented
oh iya berarti bener `GET /venue` tapi karena private dari venue, harus include venueId di Query DynamoDB nya @hapehatelo

2021-06-06 12:31 UTC, hapehatelo commented
o

> oh iya berarti bener `GET /venue` tapi karena private dari venue, harus include venueId di Query DynamoDB nya @hapehatelo

oh kalo list discount yang diakses berdasarkan venueId yg login itu udah dibuat aldy di `GET /`
kalo yang buat diakses public belum ada @JuniYadi

2021-06-08 01:20 UTC, JuniYadi commented
> > oh iya berarti bener `GET /venue` tapi karena private dari venue, harus include venueId di Query DynamoDB nya @hapehatelo
> 
> oh kalo list discount yang diakses berdasarkan venueId yg login itu udah dibuat aldy di `GET /`
> kalo yang buat diakses public belum ada @JuniYadi

oh iya sih, tapi di spreadsheet ini venue soalnya.
aq merge dulu aja kalau gitu

2021-06-08 01:21 UTC, merged